alioth: Exclude QCOM powerhal manifest
- Build error logs:
  getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/power.xml: HAL "android.hardware.power" has a conflict: Conflicting FqInstance: IPower/default (@4) (from /vendor/etc/vintf/manifest/android.hardware.power-service.lineage.xml) vs. IPower/default (@4) (from /vendor/etc/vintf/manifest/power.xml). Check whether or not multiple modules providing the same HAL are installed.
  Unable to print HALs from new FCMs: no device HAL manifest.
  ERROR: No such device: No device manifest file from device or from update package
  No device manifest.
  No device HAL manifest
  Missing device manifest.: No such file or directory: No such device

Co-authored-by: kondors1995 <normandija1945@gmail.com>